USE customer_shopping_behaviour

SELECT TOP 20 * FROM dbo.customer_data 

--Q1. What is the total revenue generated by male vs female customers?

SELECT gender, SUM(purchase_amount) AS revenue
FROM dbo.customer_data GROUP BY gender

--Q2. which customer used a discount but still spent more than average purchase amount?

SELECT customer_id, purchase_amount
FROM dbo.customer_data
WHERE discount_applied = 'yes' and purchase_amount >= (SELECT AVG(purchase_amount) FROM dbo.customer_data)

--Q3. which are the top 5 products with the highest average review rating?

SELECT TOP 5 item_purchased,ROUND(AVG(review_rating),2) AS avg_review_rating
FROM dbo.customer_data
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC

--Q4. compare the average purchase amount between standard and express shipping?

SELECT shipping_type, AVG(purchase_amount)
FROM dbo.customer_data
WHERE shipping_type in ('Standard','Express')
GROUP BY shipping_type

--Q5. Do subscribed customers spend more? compare average spent and total revenue between subscribers and non subscribers.
SELECT subscription_status,
COUNT(customer_id) AS total_customers,
AVG(purchase_amount) AS average_spend,
SUM(purchase_amount) AS total_revenue
FROM dbo.customer_data
GROUP BY subscription_status

--Q6. which 5 products have the highest percentage of purchases with discounts applied?

SELECT TOP 5 item_purchased,
100 * SUM(CASE WHEN discount_applied = 'yes' THEN 1 ELSE 0 END)/COUNT(*) AS purchase_percent
FROM dbo.customer_data
GROUP BY item_purchased
ORDER BY purchase_percent DESC

--Q7. Segments customers into new, returning, and loyal based on their total number of
--previous purchases, and show the count of each segment.

WITH segmented_data AS(
SELECT customer_id, previous_purchases,
CASE WHEN previous_purchases = 1 THEN 'new'
WHEN previous_purchases BETWEEN 2 AND 10 THEN 'returning'
ELSE 'loyal'
END AS customer_segment
FROM dbo.customer_data)

SELECT customer_segment,
COUNT(*) AS number_of_customers
FROM segmented_data
GROUP BY customer_segment

--Q8 what are the top 3 most purchased products within each category?

WITH item_counts AS (
SELECT category, item_purchased,
COUNT(customer_id) AS total_orders,
ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
FROM dbo.customer_data
GROUP BY category,item_purchased
)

SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <= 3

--Q9 Are customers repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT subscription_status,
COUNT(customer_id) AS repeat_buyers
FROM dbo.customer_data
WHERE previous_purchases > 5
GROUP BY subscription_status

--Q10. What is the revenue contribuition of each age group?

SELECT age_group,
SUM(purchase_amount) AS revenue_gen
FROM dbo.customer_data
GROUP BY age_group
ORDER BY revenue_gen DESC